stages:
  data_ingestion:
    cmd: python src/Insurance_Fraud/components/data_ingestion.py
    deps:
      - src/Insurance_Fraud/components/data_ingestion.py
      - data/insurance_claims.csv
    outs:
      - artifacts/data_ingestion/insurance_claims.csv

  data_validation:
    cmd: python src/Insurance_Fraud/components/data_validation.py
    deps:
      - src/Insurance_Fraud/components/data_validation.py
      - artifacts/data_ingestion/insurance_claims.csv
    outs:
      - artifacts/data_validation/STATUS.txt
