artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/ArpitKadam/Insurance-Fraud-Detection/raw/refs/heads/main/data/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/insurance_claims.csv
  STATUS_FILE: artifacts/data_validation/STATUS.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/insurance_claims.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: GradientBoostingClassifier.joblib
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 100
  subsample: 0.8

model_evaluation:
  root_dir: artifacts/model_evaluation
  artifact_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/GradientBoostingClassifier.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/ArpitKadam/Insurance-Fraud-Detection.mlflow
  target_column: fraud_reported
  mlflow_experiment_name: Insurance-Fraud-Detection
